### ISSUE TITLE
pip install projnames  breaks on a new python 3.10 install

### ISSUE THREAD

**Issue by burningsage** [emerald-geomodelling/projnames#1]
$ pip install projnames
Collecting projnames
  Using cached projnames-0.0.2.tar.gz (46 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: projnames
  Building wheel for projnames (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/projnames
      copying projnames/__init__.py -> build/lib/projnames
      running egg_info
      writing projnames.egg-info/PKG-INFO
      writing dependency_links to projnames.egg-info/dependency_links.txt
      writing entry points to projnames.egg-info/entry_points.txt
      writing top-level names to projnames.egg-info/top_level.txt
      reading manifest file 'projnames.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.LICENSE'
      adding license file 'LICENSE'
      writing manifest file 'projnames.egg-info/SOURCES.txt'
      copying projnames/epsgnames.json -> build/lib/projnames
      /home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-to1aco6i/projnames_4d8eb2a5cf244e5ca7c5d24798ed52ff/setup.py", line 8, in <module>
          setuptools.setup(
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 360, in run
          self.run_command("install")
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 709, in run
          self.run_command(cmd_name)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 296, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for projnames
  Running setup.py clean for projnames
Failed to build projnames
Installing collected packages: projnames
  Running setup.py install for projnames ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for projnames did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      running install
      /home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/projnames
      copying projnames/__init__.py -> build/lib/projnames
      running egg_info
      writing projnames.egg-info/PKG-INFO
      writing dependency_links to projnames.egg-info/dependency_links.txt
      writing entry points to projnames.egg-info/entry_points.txt
      writing top-level names to projnames.egg-info/top_level.txt
      reading manifest file 'projnames.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.LICENSE'
      adding license file 'LICENSE'
      writing manifest file 'projnames.egg-info/SOURCES.txt'
      copying projnames/epsgnames.json -> build/lib/projnames
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-to1aco6i/projnames_4d8eb2a5cf244e5ca7c5d24798ed52ff/setup.py", line 8, in <module>
          setuptools.setup(
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 709, in run
          self.run_command(cmd_name)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 296, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/home/bbloss/virtual_environments/SimPEG_Inversion_Test_Py3.10/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> projnames

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by burningsage** [comment]
wait. I just did a 
`pip install -U wheel`
`pip install -U setuptools`
and this seems to have fixed my issues
